@apiEndpoint = http://localhost:{{$dotenv PORT}}


### Products
GET {{apiEndpoint}}/products

### One product
GET {{apiEndpoint}}/products/4

### Product to update
GET {{apiEndpoint}}/products/update/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA4NDIwNDAzLCJleHAiOjE3MDg1MDMyMDN9.YDQ3xNyfqD1Uo8C7b7Mqr8yvgYJsGxJ9JoNDxdGS7rw

### Categories
GET {{apiEndpoint}}/categories/

### One category
GET {{apiEndpoint}}/categories/3

### Products of Category
GET {{apiEndpoint}}/categories/3/products

### Orders
GET {{apiEndpoint}}/orders
Authorization: Bearer <Your_Token_Here>

### One order
GET {{apiEndpoint}}/orders/2
Authorization: Bearer <Your_Token_Here>

### Users
GET {{apiEndpoint}}/users

### One user account
GET {{apiEndpoint}}/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA5MjA3NDg4LCJleHAiOjE3MDkyOTAyODh9.te_nfpzdB98GzDdPh5BAN4PXOccNWSUtbNi1K-5fVn0

### Orders of user account
GET {{apiEndpoint}}/users/2/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAwMTQwMTA5LCJleHAiOjE3MDAyMjI5MDl9.Y3CUM-YorupZkwU7mjckxtqR6kN-rd118gP20w16cNM

### Modify User 1
PATCH  {{apiEndpoint}}/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA5ODI5MjEwLCJleHAiOjE3MDk5MTIwMTB9.oUZobPgX4prmNDSR9bpWKjMpsGBb2jlikJMgUzuwAuI

{  
   "first_name": "Serge",
   "last_name": "Serge",
   "phone": "0606060605",
   "email": "tessst@test.com"
 }

### Modify Status Order 1
PATCH {{apiEndpoint}}/orders/1/update-status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA4NDI2NDQ5LCJleHAiOjE3MDg1MDkyNDl9.iJXCW2ebdN5Da2gj47rNlxOSToSB_swD2JmwzPjgzBU

{
    "status": "en cours"
}

### Modify Categories of a product 1
PATCH {{apiEndpoint}}/products/1/categories
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{
    "categoryIds": [1, 2, 3]
}

### Modify Url Medias for 1 product
PATCH {{apiEndpoint}}/products/1/media
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{
    "newMediaUrls": [
        {"url": "http://example.com/image1.jpg", "name": "Image 1"},
        {"url": "http://example.com/image2.jpg", "name": "Image 2"}
    ]
}

### Modify Product 1
PATCH  {{apiEndpoint}}/products/1
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{  
   "name" : "test 1", 
   "scientific_name" : "test 2", 
   "maturity_height" : "test",
   "maturity_width": "test",
   "family": "test", 
   "origin": "test",
   "flower_color": "test",  
   "leaf_color": "test",
   "description1": "test",
   "description2": "test",
   "stock" : 6,
	"price" : 25,
	"vat" : 20.00,
	"status": false,  
	"yield_id": 1,
	"hardiness_zone_id": 1,
	"water_requirement_id": 1,
	"exposure_id": 1, 
   "ground_cover_power_id": 1, 
	"strate_id" : 1,
	"foliage_id": 1 
 }

### Product creation
POST {{apiEndpoint}}/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA4NDIwMjM0LCJleHAiOjE3MDg1MDMwMzR9.gRWB0F0LRUHB7MPSIJs8_xIUoSP5MOgCZWdYhzKoCE0

{
   "name": "Ciboulette",
   "scientific_name": "ALLIUM schoenoprasum",
   "maturity_height": "200 cm",
   "maturity_width": "160 cm",
   "family": "boum",
   "origin": "tutu",
   "flower_color": "rouge",
   "leaf_color": "orenge",
   "description1": "En été, les tiges creuses, dressées et odorantes de la ciboulette portent jusqu'à 20 fleurs violet clair ou roses disposées en ombelle dense et pouvant atteindre jusqu'à 5 cm d'envergure. Allium schoenoprasum est une plante vivace bulbeuse, comestible (tiges et fleurs), facile à vivre, utilisée comme condiment. Il est toutefois préférable de couper les fleurs avant qu'elles ne montent en graines.Plantation Exposition soleil, mi-ombre, rusticité rustique (t° mini : -15°), type de sol normal, richesse du sol pauvre, humidité du sol frais, ph du sol tous\n\nTous nos conseils de plantation\nCaractéristiques\nPlante, hauteur à maturité 25 cm, largeur à maturité 10 cm, couleur du feuillage vert tendre, type de feuillage semi-persistant, port hérissée\n\nCaractéristiques complètes",
   "description2": "il n'y en a pas",
   "size": "11 cm",
   "pot": "1L",
   "stock": 15,
   "price": 2.6,
   "vat": 10,
   "status": false,
   "user_id": 1,
   "yield_id": 1,
   "hardiness_zone_id": 1,
   "water_requirement_id": 1,
   "exposure_id": 1,
   "ground_cover_power_id": 1,
   "strate_id": 1,
   "foliage_id": 1
 }

### User creation
POST {{apiEndpoint}}/users/
Content-Type: application/json

{
   "first_name": "test",
   "last_name": "essai",
   "email": "test@test.com",
   "password": "Tes4*" 
}

### Media creation
POST {{apiEndpoint}}/products/media
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjk5OTQ4NDYzLCJleHAiOjE3MDAwMzEyNjN9.jWiZ9JQznwPU2Gp1dLog4sNsXhm6OGaeTeFGgNh93ls
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="plante-terre.jpg"
Content-Type: image/jpeg

@/docs/send/plante.terre.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Product_has_media creation
POST {{apiEndpoint}}/products/media/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywicm9sZSI6InVzZXIiLCJpYXQiOjE2OTk3MDg5NDMsImV4cCI6MTY5OTcxMjU0M30.y8zIXx3oC_jo2c2iIhD795GBVJlEonlXebPDwT6E158

[
 {
    "product_id": 1,
    "media_id": 1,
    "order": 1
 },
 {
    "product_id": 2,
    "media_id": 2,
    "order": 1
 }
]

### order creation
POST {{apiEndpoint}}/orders/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAwMDU0NzE0LCJleHAiOjE3MDAxMzc1MTR9.9s3d55LcC93EKmyQBMNofPjmBsprVc3m6NgNXuul-4M

{
   "first_name_order": "blublu",
   "last_name_order": "bloblo",
   "total_price": 150.12,
   "status": "validé",
   "user_id": 1
}

### order_has_product creation
POST {{apiEndpoint}}/orders/details
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAwMDU0NzE0LCJleHAiOjE3MDAxMzc1MTR9.9s3d55LcC93EKmyQBMNofPjmBsprVc3m6NgNXuul-4M

[
 {
    "product_id": 1,
    "order_id": 1,
    "quantity": 12,
    "price_time_order": 12.52,
    "vat": 5.5
 },
 {
    "product_id": 2,
    "order_id": 2,
    "quantity": 10,
    "price_time_order": 2.52,
    "vat": 20
 }
]

### Product_has_category creation
POST {{apiEndpoint}}/products/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAwMDU0NzE0LCJleHAiOjE3MDAxMzc1MTR9.9s3d55LcC93EKmyQBMNofPjmBsprVc3m6NgNXuul-4M

{
   "product_id": 1,
   "category_id": 1
}

### Register User
POST {{apiEndpoint}}/users/register
Content-Type: application/json

{
  "phone": "0606060606",
  "first_name": "essaie",
  "last_name": "test",
  "email": "test@test.com",
  "password": "Test1234*"
  //"role": "admin"
}


### Login User
POST {{apiEndpoint}}/users/login
Content-Type: application/json

{
   "email": "pepine@gmail.com",
   "password": "Pepine12345*"
}
### media delete
DELETE {{ apiEndpoint }}/products/media/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAwMDU0MDE3LCJleHAiOjE3MDAxMzY4MTd9.JrGSIQv04NpB2CmWNq6FtK3sBFYixQDHIw9Hy3p9aaM


### user delete
DELETE {{ apiEndpoint }}/users/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicm9sZSI6InVzZXIiLCJpYXQiOjE2OTk2MjAwODEsImV4cCI6MTY5OTYyMzY4MX0.69VPI-0yVTRGedtceVTAbBZTBNdzBzRTFx08b2H8T6s

{
  "targetId": 7
}

### productHasCategory delete
DELETE {{ apiEndpoint }}/products/1/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAyOTA5NjI4LCJleHAiOjE3MDI5OTI0Mjh9.3Sl4DWoeVSAbq28yus5Si-o2pIweBYp712Mc4u1pCBI

### forgot password
POST {{apiEndpoint}}/users/forgot-password
Content-Type: application/json

{
   "email": "pa@gmail.com"
}

### reset password
POST {{apiEndpoint}}/users/reset-password
Content-Type: application/json

{ 
   "newPassword": "Test123*",
   "resetToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTcwODUwNTE4MiwiZXhwIjoxNzA4NTA4NzgyfQ.3HyRXc7NOIbSyWx20i4DaT_FvyM6xdvXwZbqqxrbh0A"
}

### delete category by product_id
DELETE {{apiEndpoint}}/categories/product/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA5MDIyMTg0LCJleHAiOjE3MDkxMDQ5ODR9.VHKIhM4Wqtmqv11PkkzRiOnzoe6ujxakifuUl2UPt8I

### change password
POST {{apiEndpoint}}/users/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA5MTA2Njc4LCJleHAiOjE3MDkxODk0Nzh9.dz2nHXei4PWo6DZ5XO6EsynZo2sZP0i-DFMfkgB_iD0

{
   "oldPassword": "Pepine12345*",
   "newPassword": "Test12345*"
}