@apiEndpoint = http://localhost:{{$dotenv PORT}}

### Products
GET {{apiEndpoint}}/products

### One product
GET {{apiEndpoint}}/products/4

### Categories
GET {{apiEndpoint}}/categories/

### One category
GET {{apiEndpoint}}/categories/3

### Products of Category
GET {{apiEndpoint}}/categories/3/products

### Orders
GET {{apiEndpoint}}/orders
Authorization: Bearer <Your_Token_Here>

### One order
GET {{apiEndpoint}}/orders/2
Authorization: Bearer <Your_Token_Here>

### Users
GET {{apiEndpoint}}/users

### One user account
GET {{apiEndpoint}}/users/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjk5NDU2NjMyLCJleHAiOjE2OTk0NjAyMzJ9.JcatDncMbCHT9fkKJw9KEKucf1Nt4AoOUlfZO_D8yJM

### Orders of user account
GET {{apiEndpoint}}/users/3/orders

### Modify User 1
PATCH  {{apiEndpoint}}/users/1
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{  
   "first_name": "Serge",
   "last_name": "Serge",
   "email": "test@test.com",
   "password": "test"
 }

### Modify Status Order 1
PATCH {{apiEndpoint}}/orders/1/update-status
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{
    "newStatus": "validé"
}

### Modify Categories of a product 1
PATCH {{apiEndpoint}}/products/1/categories
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{
    "categoryIds": [1, 2, 3]
}

### Modify Url Medias for 1 product
PATCH {{apiEndpoint}}/products/1/media
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{
    "newMediaUrls": [
        {"url": "http://example.com/image1.jpg", "name": "Image 1"},
        {"url": "http://example.com/image2.jpg", "name": "Image 2"}
    ]
}

### Modify Product 1
PATCH  {{apiEndpoint}}/products/1
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{  
   "name" : "test 1", 
   "scientific_name" : "test 2", 
   "maturity_height" : "test",
   "maturity_width": "test",
   "family": "test", 
   "origin": "test",
   "flower_color": "test",  
   "leaf_color": "test",
   "description1": "test",
   "description2": "test",
   "stock" : 6,
	"price" : 25,
	"vat" : 20.00,
	"status": false,  
	"yield_id": 1,
	"hardiness_zone_id": 1,
	"water_requirement_id": 1,
	"exposure_id": 1, 
   "ground_cover_power_id": 1, 
	"strate_id" : 1,
	"foliage_id": 1 
 }

### Product creation
POST {{apiEndpoint}}/products/
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{
   "name": "Ciboulette",
   "scientific_name": "ALLIUM schoenoprasum",
   "maturity_height": "200 cm",
   "maturity_width": "160 cm",
   "family": "boum",
   "origin": "tutu",
   "flower_color": "rouge",
   "leaf_color": "orenge",
   "description1": "En été, les tiges creuses, dressées et odorantes de la ciboulette portent jusqu'à 20 fleurs violet clair ou roses disposées en ombelle dense et pouvant atteindre jusqu'à 5 cm d'envergure. Allium schoenoprasum est une plante vivace bulbeuse, comestible (tiges et fleurs), facile à vivre, utilisée comme condiment. Il est toutefois préférable de couper les fleurs avant qu'elles ne montent en graines.Plantation Exposition soleil, mi-ombre, rusticité rustique (t° mini : -15°), type de sol normal, richesse du sol pauvre, humidité du sol frais, ph du sol tous\n\nTous nos conseils de plantation\nCaractéristiques\nPlante, hauteur à maturité 25 cm, largeur à maturité 10 cm, couleur du feuillage vert tendre, type de feuillage semi-persistant, port hérissée\n\nCaractéristiques complètes",
   "description2": "il n'y en a pas",
   "stock": 15,
   "price": 2.6,
   "vat": 10,
   "status": "false",
   "user_id": 1,
   "yield_id": 1,
   "hardiness_zone_id": 1,
   "water_requirement_id": 1,
   "exposure_id": 1,
   "ground_cover_power_id": 1,
   "strate_id": 1,
   "foliage_id": 1
 }

### User creation
POST {{apiEndpoint}}/users/
Content-Type: application/json

{
   "first_name": "test",
   "last_name": "essai",
   "email": "test@test.com",
   "password": "adzedhafhgfdsddsfdththdcdfvfvfzefdaheriufrt5t19619819rt" 
}

### Media creation
POST {{apiEndpoint}}/products/media
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

[
 {
    "url": "https://www.naturephotographie.com/wp-content/uploads/2019/02/Rays-of-Light-on-the-Summit-1461x975.jpg",
    "name": "test"
 },
 {
    "url": "https://www.mangiarebuono.it/wp-content/uploads/2016/02/ananas3.jpg",
    "name": "essai"
 }
]

### Product_has_media creation
POST {{apiEndpoint}}/products/media/order
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

[
 {
    "product_id": 1,
    "media_id": 1,
    "order": 1
 },
 {
    "product_id": 2,
    "media_id": 2,
    "order": 1
 }
]

### order creation
POST {{apiEndpoint}}/orders/
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{
   "first_name_order": "blublu",
   "last_name_order": "bloblo",
   "total_price": 150.12,
   "status": "validé",
   "user_id": 1
}

### order_has_product creation
POST {{apiEndpoint}}/orders/details
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{
   "product_id": 1,
   "order_id": 1,
   "quantity": 12,
   "price_time_order": 12.52,
   "vat": 5.5
}

### Product_has_category creation
POST {{apiEndpoint}}/products/category
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{
   "product_id": 1,
   "category_id": 1
}

### Register User
POST {{apiEndpoint}}/users/register
Content-Type: application/json

{
  "first_name": "super",
  "last_name": "pepine",
  "email": "pepine@gmail.com",
  "password": "Pepine12345*",
  //"role": "admin"
}


### Login User
POST {{apiEndpoint}}/users/login
Content-Type: application/json

{
   "email": "pepine@gmail.com",
   "password": "Pepine12345*"
}
### media delete
DELETE {{ apiEndpoint }}/products/media/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk5NjE0NjQ2LCJleHAiOjE2OTk2MTgyNDZ9.i71DnEdYPmdUK9IWuZDhcRb-CFpV9CXuMeOrfEvGkQo


### user delete
DELETE {{ apiEndpoint }}/users/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNjk5NTI4NzY4LCJleHAiOjE2OTk1MzIzNjh9.Bta1N1clHPl3bvmz4jqWyK-Rf53J24TFf1CL_e9GGic

{
  "targetId": 7
}